// Online Java Compiler
// Use this editor to write, compile and run your Java code online

class Main {
    public static void main(String[] args) {
        System.out.printlnaclass thsdemo; {
    int num = 3;

    public void set() {
        num++;
    }

    public void get() {
        System.out.print(num + " ");
    }
}

public class Main {
    public static void main(String[] args) {
        // Create three objects of thsdemo class
        thsdemo ob1 = new thsdemo();
        thsdemo ob2 = new thsdemo();
        thsdemo ob3 = new thsdemo();

        ob1.set();
        ob1.set();
        ob2.set();
        ob3.set();
        ob3.set();

        ob1.get();
        ob2.get();
        ob3.get();
    }
}
